# Doctrine mapping, entity configuration xml Driver
services:
  sexy_field.xml_driver:
    class: Doctrine\ORM\Mapping\Driver\XmlDriver
    arguments:
      -
        - "%kernel.project_dir%/vendor/tardigrades/sexy-field/src/config/xml"
      - ".dcm.xml"

  # This is the configuration that assumes you use the sexy-field-doctrine and sexy-field-entity package
  # If you have more generators, or more readers and writers, override this configuration
  # in your own application services configuration.
  Tardigrades\SectionField\Generator\Generators:
    arguments:
      -
        - '@section_field.generator.entity_generator'
        - '@section_field.generator.entity_trait_generator'
        - '@section_field.generator.entity_serializer_generator'
        - '@section_field.generator.doctrine_config_generator'

  section_field.generator: '@Tardigrades\SectionField\Generator\Generators'

  Tardigrades\SectionField\Service\CreateSection:
    public: true
    arguments:
      -
        - '@section_field.doctrine.create.section'
      - '@event_dispatcher'
      - '@default.cache'

  section_field.create.section: '@Tardigrades\SectionField\Service\CreateSection'

  Tardigrades\SectionField\Service\ReadSection:
    public: true
    arguments:
      -
        - '@section_field.doctrine.read.section'
      - '@section_field.manager.doctrine.section_manager'
      - '@event_dispatcher'

  section_field.read.section: '@Tardigrades\SectionField\Service\ReadSection'

  Tardigrades\SectionField\Service\DeleteSection:
    public: true
    arguments:
      -
        - '@section_field.doctrine.delete.section'
      - '@event_dispatcher'

  section_field.delete.section: '@Tardigrades\SectionField\Service\DeleteSection'

  HTMLPurifier:
    class: \HTMLPurifier

  Tardigrades\Bundle\SexyFieldBundle\SectionField\Purifier\CacheWarmer\SerializerCacheWarmer:
    public: false
    arguments:
      - [ '%kernel.cache_dir%/htmlpurifier' ]
      - '@HTMLPurifier'
    tags: [ kernel.cache_warmer ]

